services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "1884:1884"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
