services:
  kicker-backend:
    build: ../backend
    container_name: kicker-backend
    restart: unless-stopped
    networks:
      - emqx
    volumes:
      - ./config/backend:/home/bun/app/resources
      - ./data/backend:/data

  kicker-frontend:
    build: ../frontend
    container_name: kicker-frontend
    restart: unless-stopped
    ports:
      - 80:80
    labels:
      traefik.enable: "true"
      traefik.http.routers.kicker.rule: Host("kicker.local.hiqs.de")
    volumes:
      - ./config/frontend/config.json:/srv/assets/config.json

networks:
  emqx:
    external: true
