import {TeamColor} from "../../../models/team";

export enum GameEventType {

  _SCORE = "SCORE",
  _INCREASE = "INCREASE",
  _DECREASE = "DECREASE",
  _CHANGE = "CHANGE",

  SCORE_CHANGE = `${_SCORE}.${_CHANGE}`,

  WHITE_SCORE_CHANGE = `${TeamColor.WHITE}.${SCORE_CHANGE}`,
  BLACK_SCORE_CHANGE = `${TeamColor.BLACK}.${SCORE_CHANGE}`,

  SCORE_INCREASE = `${_SCORE}.${_INCREASE}`,
  SCORE_DECREASE = `${_SCORE}.${_DECREASE}`,

  WHITE_SCORE_INCREASE = `${TeamColor.WHITE}.${SCORE_INCREASE}`,
  WHITE_SCORE_DECREASE = `${TeamColor.WHITE}.${SCORE_DECREASE}`,
  BLACK_SCORE_INCREASE = `${TeamColor.BLACK}.${SCORE_INCREASE}`,
  BLACK_SCORE_DECREASE = `${TeamColor.BLACK}.${SCORE_DECREASE}`,

  _WINNER = "WINNER",

  WINNER_CHANGE = `${_CHANGE}.${_WINNER}`
}
