export enum PlayerEventType {

  WHITE_PLAYER_REGISTER_TO_GAME = "WHITE_PLAYER_REGISTER_TO_GAME",
  BLACK_PLAYER_REGISTER_TO_GAME = "BLACK_PLAYER_REGISTER_TO_GAME",
  PLAYER_CHANGE_NAME = "PLAYER_CHANGE_NAME"

}