name: AsyncAPI documents processing

on:
  push:
    branches: [ "develop", "main", "**pages**", "9-update-gitlab-cli-to-github-action-pages" ]


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-generator