name: AsyncAPI documents processing

on:
  push:
    branches: [ "develop", "main", "**pages**", "9-update-gitlab-cli-to-github-action-pages" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-cli@v3.1.1 # You can use any version you want
        with:
          command: generate
          filepath: ./backend/asyncapi.yaml
          template: "@asyncapi/html-template@0.9.0" #In case of template from npm. Or can use a link.
          output: ./generated-html
          parameters: "-p baseHref=/test-experiment/ sidebarOrganization=byTags"

      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated-html