name: AsyncAPI documents processing

on:
  push:
    branches: [ "develop", "main", "**pages**", "9-update-gitlab-cli-to-github-action-pages" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generator, Validator, Converter and others - all in one for your AsyncAPI docs
        uses: asyncapi/github-action-for-cli@v3.0.0
