name: AsyncAPI documents processing

on:
  push:
    branches: [ "develop", "main", "**pages**", "9-update-gitlab-cli-to-github-action-pages" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generator, Validator, Converter and others - all in one for your AsyncAPI docs
        uses: asyncapi/github-action-for-cli@v3.1.1
        with:
          command: generate
          filepath: ./backend/asyncapi.yaml
          template: "@asyncapi/html-template" #In case of template from npm. Or can use a link.
          output: ./asyncapi-generated-html
          parameters: "-p baseHref=/test-experiment/ sidebarOrganization=byTags"

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./asyncapi-generated-html
