name: Run bun tests for backend
on: push
jobs:
  test_job:
    name: test_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.12

      - run: ls
      - run: |
          cd backend
          bun install
          bun build --target=bun /src/app.ts
          bun test