digkick:
  banner: false

mqtt:
  login:
    username: test
    password: test
  host: localhost

db:
  source:
    database:
      name: database
      suffix: db

player:
  name:
    restrictions:
      length:
        min: 3
        max: 16
